spring.application.name=ms-category
server.port=8086

# ==========================================
# Conexión a la Base de Datos (Laragon)
# ==========================================
# Recuerda que la base de datos se llama db_reviews en tu Laragon (puerto 3307 por lo visto en tu log)
spring.datasource.url=jdbc:mysql://localhost:3306/db_category?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
# En Laragon la contraseña por defecto va vacía:
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Configuración de JPA / Hibernate

# 'update' creará automáticamente la tabla 'cart' si no la creaste manualmente en HeidiSQL
spring.jpa.hibernate.ddl-auto=update
# Muestra y formatea las consultas SQL en la terminal para que revises qué se está guardando
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Configuración Extra

# Desactiva Flyway si no lo estás usando para el control de versiones de la BD
spring.flyway.enabled=false