spring.application.name=ms-cart
server.port=8087
#  la base de datos se llama db_reviews en tu Laragon (puerto 3307 por lo visto en tu log)
spring.datasource.url=jdbc:mysql://localhost:3306/db_cart?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
# En Laragon la contraseña por defecto va vacía:
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# 'update' crea automáticamente la tabla 'cart' 
spring.jpa.hibernate.ddl-auto=update
# Muestra y formatea las consultas SQL en la terminal 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Desactiva Flyway si no lo estás usando 
spring.flyway.enabled=false