server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            # --- 1. USUARIOS ---
            - id: ruta-usuarios-docs
              uri: lb://ms-user
              predicates:
                - Path=/api/usuarios/v3/api-docs
              filters:
                - RewritePath=/api/usuarios/v3/api-docs, /v3/api-docs
            - id: ruta-usuarios
              uri: lb://ms-user
              predicates:
                - Path=/api/usuarios/**
              filters:
                - RewritePath=/api/usuarios(?<segment>/?.*), /api/v1/usuarios${segment}

            # --- 2. PRODUCTOS ---
            - id: ruta-productos-docs
              uri: lb://MS-PRODUCT
              predicates:
                - Path=/api/productos/v3/api-docs
              filters:
                - RewritePath=/api/productos/v3/api-docs, /v3/api-docs
            - id: ruta-productos
              uri: lb://MS-PRODUCT
              predicates:
                - Path=/api/productos/**
              filters:
                - RewritePath=/api/productos(?<segment>/?.*), /api/v1/productos${segment}

            # --- 3. ORDENES ---
            - id: ruta-ordenes-docs
              uri: lb://MS-ORDER
              predicates:
                - Path=/api/ordenes/v3/api-docs
              filters:
                - RewritePath=/api/ordenes/v3/api-docs, /v3/api-docs
            - id: ruta-ordenes
              uri: lb://MS-ORDER
              predicates:
                - Path=/api/ordenes/**
              filters:
                - RewritePath=/api/ordenes(?<segment>/?.*), /api/v1/ordenes${segment}

            # --- 4. PAGOS ---
            - id: ruta-pagos-docs
              uri: lb://MS-PAYMENT
              predicates:
                - Path=/api/pagos/v3/api-docs
              filters:
                - RewritePath=/api/pagos/v3/api-docs, /v3/api-docs
            - id: ruta-pagos
              uri: lb://MS-PAYMENT
              predicates:
                - Path=/api/pagos/**
              filters:
                - RewritePath=/api/pagos/?(?<segment>.*), /api/v1/pagos/${segment}

            # --- 5. ENVIOS ---
            - id: ruta-envios-docs
              uri: lb://MS-SHIPPING
              predicates:
                - Path=/api/envios/v3/api-docs
              filters:
                - RewritePath=/api/envios/v3/api-docs, /v3/api-docs
            - id: ruta-envios
              uri: lb://MS-SHIPPING
              predicates:
                - Path=/api/envios/**
              filters:
                - RewritePath=/api/envios/?(?<segment>.*), /api/v1/envios/${segment}

            # --- 6. CATEGORIAS ---
            - id: ruta-categorias-docs
              uri: lb://MS-CATEGORY
              predicates:
                - Path=/api/categorias/v3/api-docs
              filters:
                - RewritePath=/api/categorias/v3/api-docs, /v3/api-docs
            - id: ruta-categorias
              uri: lb://MS-CATEGORY
              predicates:
                - Path=/api/categorias/**
              filters:
                - RewritePath=/api/categorias/?(?<segment>.*), /api/v1/category/${segment}

            # --- 7. RESENAS ---
            - id: ruta-resenas-docs
              uri: lb://MS-REVIEW
              predicates:
                - Path=/api/resenas/v3/api-docs
              filters:
                - RewritePath=/api/resenas/v3/api-docs, /v3/api-docs
            - id: ruta-resenas
              uri: lb://MS-REVIEW
              predicates:
                - Path=/api/resenas/**
              filters:
                - RewritePath=/api/resenas/?(?<segment>.*), /api/v1/reviews/${segment}

            # --- 8. INVENTARIO ---
            - id: ruta-inventarios-docs
              uri: lb://ms-inventario
              predicates:
                - Path=/api/inventarios/v3/api-docs
              filters:
                - RewritePath=/api/inventarios/v3/api-docs, /v3/api-docs
            - id: ruta-inventarios
              uri: lb://ms-inventario
              predicates:
                - Path=/api/inventarios/**
              filters:
                - RewritePath=/api/inventarios/?(?<segment>.*), /api/v1/inventarios/${segment}

            # --- 9. CARRITO ---
            - id: ruta-carrito-docs
              uri: lb://MS-CART
              predicates:
                - Path=/api/carrito/v3/api-docs
              filters:
                - RewritePath=/api/carrito/v3/api-docs, /v3/api-docs
            - id: ruta-carrito
              uri: lb://MS-CART
              predicates:
                - Path=/api/carrito/**
              filters:
                - RewritePath=/api/carrito/?(?<segment>.*), /api/v1/cart/${segment}

            # --- 10. SUCURSAL ---
            - id: ruta-sucursales-docs
              uri: lb://MS-SUCURSAL
              predicates:
                - Path=/api/sucursales/v3/api-docs
              filters:
                - RewritePath=/api/sucursales/v3/api-docs, /v3/api-docs
            - id: ruta-sucursales
              uri: lb://MS-SUCURSAL
              predicates:
                - Path=/api/sucursales/**
              filters:
                - RewritePath=/api/sucursales/?(?<segment>.*), /api/v1/sucursales/${segment}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    urls:
      - name: Microservicio Usuarios
        url: /api/usuarios/v3/api-docs
      - name: Microservicio Productos
        url: /api/productos/v3/api-docs
      - name: Microservicio Inventario
        url: /api/inventarios/v3/api-docs
      - name: Microservicio Sucursales
        url: /api/sucursales/v3/api-docs
      - name: Microservicio Pagos
        url: /api/pagos/v3/api-docs
      - name: Microservicio Ordenes
        url: /api/ordenes/v3/api-docs
      - name: Microservicio Resenas
        url: /api/resenas/v3/api-docs
      - name: Microservicio Envíos 
        url: /api/envios/v3/api-docs
      - name: Microservicio Carrito de Compras
        url: /api/carrito/v3/api-docs
      - name: Microservicio Categorías
        url: /api/categorias/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/