spring.application.name=ms-user


server.port=8081

# Configuración de la base de datos en Laragon
spring.datasource.url=jdbc:mysql://localhost:3306/db_user?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
# En Laragon la contraseña por defecto viene vacía (borra lo que tengas y déjalo así):
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate (JPA) para que cree las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true